- app/views/main.html
Say heavy clients rather than fat clients.
> Typos, requests, text change

- app/index.html
Switch from dunglas/api-platform to api-platform/api-platform
> Fix Github link

- static/schema/metadata/metadata-2.0.xsd
Fix #13, api-platform/docs#255
> Create metadata-2.0.xsd file

- src/components/home/AllInOne.js
- src/components/home/Ecosystem.js
- src/components/home/Giants.js
- src/components/home/Schema.js
- src/data/schema.js
ping @ginifizz (the new wording)
> Update the website to match API Platform 2.2 features

- src/components/home/Giants.js
> Add missing spaces

- gatsby-node.js
> remove trailing index in links

- bin/retrieve-documentation
- gatsby-node.js
- src/templates/doc.js
> Add edit page links

- bin/retrieve-documentation
- src/templates/doc.js
> fix edit on github links

- gatsby-node.js
> travis test

- src/lib/treeHelper.js
Réf : https://github.com/api-platform/docs/issues/615
> innerHTML->textContent

- src/components/layout/Search.js
- src/html.js
> Fix issue caused by update on the version 2.6 of docsearch library

- gatsby-config.js
> disable gatsby-offline until cache issues is fixed

- gatsby-node.js
Edit link is not working (bottom of every doc pages)
This is a quick fix, maybe we need to have a cleaner solution later
> edit link quick fix

- src/components/layout/Logo.js
> Fix Logo title

- gatsby-config.js
- package.json
- yarn.lock
See more at https://github.com/francoischalifour/medium-zoom
> Add plugin for zooming images

- gatsby-config.js
- package.json
- yarn.lock
Reverts api-platform/website#155
> Revert "Add plugin for zooming images"

- src/pages/docs.js
- src/styles/components/_docs.scss
Fixes for https://github.com/api-platform/website/pull/154#issuecomment-537940267
cc @dunglas
> Make h2 width equal to its content only for TOC

- src/styles/components/_docs.scss
> Align text list item

- src/styles/components/_docs.scss
Tiny change, but then looks better docs!
| Before   | After    |
| -------- | -------- |
| ![image](https://user-images.githubusercontent.com/4408379/66151976-17da4300-e621-11e9-9c1a-395d8617c342.png) | ![image](https://user-images.githubusercontent.com/4408379/66151987-1c9ef700-e621-11e9-93b1-3930e843696a.png) |
> Add little margin bottom for header level 2

- src/templates/doc.js
Issue #152 
Added OpenGraph  meta tag with description as page title.
> Added OpenGraph meta tag

- bin/checkout-github-template
- bin/retrieve-documentation
| Bug fix?      | no
| New feature?  | yes
| Tickets       | no
| Doc PR        | no
> Feat: Copy coc of .github repository

- src/styles/components/_docs.scss
| Bug fix?      | no
| New feature?  | no
| Tickets       | no
| Doc PR        | no
**Before**
**After**
> Fix: CSS player video

- .gitignore
| Bug fix?      | no 
| Tickets       | fixes #... 
No need of .prettierignore file as there was no code written.
> Deleted .prettierignore file

- src/components/layout/BurgerButton.js
- src/components/layout/Footer.js
- src/components/layout/Header.js
- src/components/layout/SideMenu.js
- src/html.js
- src/styles/components/_footer.scss
- src/styles/components/_header.scss
- src/styles/objects/_buttons.scss
| Bug fix?      | yes/no 
| New feature?  | yes/no 
| Deprecations? | yes/no
| Tickets       | fixes #175  
Fixes some issues related to accessibility, according to W3 validator, on homepage of api-platform website.
> Improve accessibility

- gatsby-node.js
| Bug fix?      | yes 
| Tickets       | fixes #... 
> Fix:ignore .env file on gatsby-node for production

- src/data/events.json
- src/pages/community/contributors.js
- src/pages/trademark-policy.js
- src/templates/contributor.js
| Bug fix?      | yes/no 
| New feature?  | yes/no 
| Deprecations? | yes/no
| Tickets       | fixes #... 
> Fix typos and add meetup event

- README.md
- gatsby-config.js
- gatsby-node.js
- package.json
- yarn.lock
| Bug fix?      | yes
| New feature?  | no
| Tickets       | fixes api-platform/core#3444
| Doc PR        | none
> Issue-#3444 - Feat: add redirect 301 for old page to new page

- src/pages/community.js
Hello,
This tiny PR will fix : 
- 1 typo in `src/pages/community.js`
Ciao! :robot:
> Fix typo in src/pages/community.js

- .eslintignore
- .eslintrc
- .prettierrc
- gatsby-node.js
- package.json
- src/components/Layout.js
- src/components/common/SwitchTheme.js
- src/components/community/LogoCard.js
- src/components/docs/NavItem.js
- src/components/docs/NavItemLink.js
- src/components/docs/NavSubItemLink.js
- src/components/docs/SwitchVersion.js
- src/components/home/Schema.js
- src/components/layout/DocNav.js
- src/components/layout/Footer.js
- src/components/layout/Header.js
- src/components/layout/Search.js
- src/components/layout/SideMenu.js
- src/helpers/contributorHelper.js
- src/lib/treeHelper.js
- src/lib/versionHelper.js
- src/pages/community.js
- src/pages/community/contributors.js
- src/pages/community/events.js
- src/pages/resources/logos.js
- src/pages/resources/news.js
- src/templates/contributor.js
- yarn.lock
Replaces https://github.com/api-platform/website/pull/188.
> Update ESLint config

- gatsby-config.js
- package.json
- plugins/gatsby-remark-code-selector/gatsby-browser.js
- plugins/gatsby-remark-code-selector/index.js
- plugins/gatsby-remark-code-selector/package.json
- src/styles/components/_docs.scss
- yarn.lock
| Bug fix?      | no
| New feature?  | yes
| Tickets       | N/A
| Doc PR        | N/A
> Code selector

- gatsby-node.js
Fix https://github.com/api-platform/docs/pull/1111
> fix: docs wrong link

- .eslintrc
- gatsby-node.js
| Bug fix?      | yes 
| New feature?  | yes/no 
| Deprecations? | yes/no
| Tickets       | fixes #... 
> fix: ignore markdowns without headings

- yarn.lock
> fix: bump deps

- src/components/layout/Footer.js
- src/data/menu.js
- src/pages/community.js
| Bug fix?      | no 
| New feature?  | yes 
| Doc PR        | https://github.com/api-platform/docs/pull/1165
> Add links to security-related things.

- src/components/home/Cover.js
- src/components/home/Ecosystem.js
- src/components/home/Expose.js
- src/components/home/Giants.js
- src/components/home/Schema.js
- src/data/schema.js
| Bug fix?      | no 
| Tickets       | no
> Update the homepage

- src/styles/elements/_code.scss
| Bug fix?      | yes 
| Tickets       | fixes #221
> add colors for diff

- gatsby-node.js
- src/components/con/2021/layout/Nav.tsx
- src/components/con/2021/layout/index.tsx
| Bug fix?      | yes/no 
| New feature?  | yes/no 
| Deprecations? | yes/no
| Tickets       | Fix #... 
> fix: conf links

- src/components/con/2021/Pricing/PricingCard.tsx
- src/components/con/2021/common/BuyButton.tsx
- src/components/con/2021/hooks/useEventBriteModal.tsx
- src/components/con/2021/layout/index.tsx
- src/pages/con/2021/index.tsx
- src/styles/components/con/2021/index.scss
- put html background in css inline to avoid changes on other website pages
- add condition for eventbrite widget creation to avoids double modals
- fix Event dates on structured data
| Branch?       | main 
| Bug fix?      | yes 
> fix: conf issues

- src/components/con/2021/common/Section.tsx
- src/components/con/2021/layout/index.tsx
- src/pages/con/2021/conferences/the-journey-towards-api-platform-3.md
- src/pages/con/2021/conferences/unified-permission-management-between-api-and-client.md
- add 2 speakers abstracts
- fix history state issues
> Feat: add conf abstracts for Marion and Antoine

- src/components/con/2021/Speakers/index.tsx
- src/components/con/2021/hooks/useConferences.tsx
- src/pages/con/2021/conferences/api-horror-stories-from-an-unnamed-company.md
- src/pages/con/2021/conferences/french-tech-and-startup-nation-what-else.md
- src/pages/con/2021/conferences/how-to-become-a-react-admin-grandmaster.md
- src/pages/con/2021/conferences/secure-and-practical-authentification-in-api-platform.md
- src/pages/con/2021/conferences/sylius-and-api-platform.md
- src/pages/con/2021/conferences/symfony-runtime-wrapping-api-platform-in-a-lambda.md
- src/pages/con/2021/conferences/unified-permission-management-between-api-and-client.md
- src/pages/con/2021/conferences/why-json-ld-and-what-is-it.md
> feat: last schedule changes

- src/components/con/2021/layout/index.tsx
> fix: error on price data

- src/pages/con/2021/conferences/a-suitable-serialization-with-api-platform-and-symfony.md
- src/pages/con/2021/conferences/api-horror-stories-from-an-unnamed-company.md
- src/pages/con/2021/conferences/better-php-sites-with-the-caddy-web-server.md
- src/pages/con/2021/conferences/contributing-as-a-junior-developer.md
- src/pages/con/2021/conferences/french-tech-and-startup-nation-what-else.md
- src/pages/con/2021/conferences/how-to-become-a-react-admin-grandmaster.md
- src/pages/con/2021/conferences/php-and-symfony-project-reboot.md
- src/pages/con/2021/conferences/secure-and-practical-authentification-in-api-platform.md
- src/pages/con/2021/conferences/sylius-and-api-platform.md
- src/pages/con/2021/conferences/symfony-runtime-wrapping-api-platform-in-a-lambda.md
- src/pages/con/2021/conferences/the-api-mindset-tech-product-business-legal.md
- src/pages/con/2021/conferences/the-future-of-api-platform-architecture.md
- src/pages/con/2021/conferences/the-journey-towards-api-platform-3.md
- src/pages/con/2021/conferences/unified-permission-management-between-api-and-client.md
- src/pages/con/2021/conferences/why-json-ld-and-what-is-it.md
- src/styles/components/con/2021/conference/index.scss
Adding videos to conferences' abstracts that link to their Youtube original, with a miniature.
See #263.
> feat: adding videos to conferences' abstracts

- src/components/con/2021/Review/ReviewCover.tsx
Adding this button / link so people can see the playlist on youtube.
See #264.
> feat: adding a button on the 2021 review Landing page

- src/components/community/EventCard.js
- src/pages/community/events.js
> fix: meetup key and date

- src/con/data/2022/meta.ts
Update meta title for 2022 edition
> fix: 2022 meta

- src/con/components/2021/Review/index.tsx
- src/con/components/layout/LayoutBase.tsx
- src/con/components/templates/ConferenceTemplate.tsx
- src/con/components/templates/LegalTemplate.tsx
- src/con/components/templates/SpeakerTemplate.tsx
- src/con/data/2021/faq.md
- src/con/data/2022/faq.md
- src/helmetConfig.js
- src/pages/con/2021/speakers/index.tsx
- src/pages/con/2022/index.tsx
- src/pages/con/2022/schedule.tsx
- src/pages/con/2022/speakers/index.tsx
- src/pages/index.js
| Branch?       | main| Tickets       | #... 
> feat: improve SEO

- gatsby-node.js
| Tickets       | https://github.com/api-platform/website/issues/276
> chore: redirects to state providers and processors

- bin/retrieve-documentation
> fix: disable metadata generation

- bin/retrieve-documentation
- bin/retrieve-metadata-xsd
> feat: download XSD files for v3

- constants.js
> chore: bump versions

- bin/retrieve-metadata-xsd
> fix: retrieve-metadata-xsd

- bin/retrieve-metadata-xsd
> fix: 2.7 metadata path

- README.md
- src/components/layout/Search.js
> fix: temporary fix for Algolia

- README.md
- src/components/layout/Search.js
> fix: Algolia faceting

- src/styles/vendor/_docsearchcustom.scss
| Branch?       | feature-DocSearch-v3
| Tickets       | 
| Doc PR        | 
Fix responsive problem with search modal
> Feature doc search v3

- src/components/layout/Header.js
| Branch?       | main for features
| Tickets       | #333 
| Doc PR        |
> feat: add link to api platform's mastodon

- package.json
- src/con/data/2022/conferences/4-years-later-the-components-web-app.md
- src/con/data/2022/conferences/API-platform-au-quotidien-dans-une-entreprise-e-commerce-et-logistique.md
- src/con/data/2022/conferences/building-schema-first-event-driven-architectures-with-async-api.md
- src/con/data/2022/conferences/comment-alices-garden-gere-t-elle-son-code-metier-via-les-evenements.md
- src/con/data/2022/conferences/comment-remettre-la-tech-au-service-du-bien-commun.md
- src/con/data/2022/conferences/decentralizaion-query-apis-and-other-myths.md
- src/con/data/2022/conferences/dilemmas-and-decisions-what-we-ve-learned-designing-the-new-sylius-api.md
- src/con/data/2022/conferences/domain-driven-design-with-api-platform-3.md
- src/con/data/2022/conferences/fighting-impostor-syndrome-a-pratical-handbook.md
- src/con/data/2022/conferences/finding-the-path-to-scaling-API-success.md
- src/con/data/2022/conferences/france-televisions-quand-API-Platform-tombe-a-PIC.md
- src/con/data/2022/conferences/gerer-les-operations-sequentielles-avec-REST.md
- src/con/data/2022/conferences/how-do-we-decide-to-create-a-symfony-component.md
- src/con/data/2022/conferences/la-revue-de-code-est-un-art.md
- src/con/data/2022/conferences/mon-combat-contre-l-arachnophobie.md
- src/con/data/2022/conferences/opening-keynote-a-deeper-look-into-API-platform-3.md
- src/con/data/2022/conferences/opening-keynote-introduction-to-API-platform-3.md
- src/con/data/2022/conferences/php-websockets-or-how-to-communicate-with-clients-in-real-time.md
- src/con/data/2022/conferences/pourquoi-je-n-utilise-pas-API-platform.md
- src/con/data/2022/conferences/q-a-with-api-platform-core-team.md
- src/con/data/2022/conferences/real-time-and-beyond-with-mercure.md
- src/con/data/2022/conferences/reutiliser-et-partager-vos-operations-API-platform-personnalisées.md
- src/con/data/2022/conferences/tests-avances.md
- src/con/data/2022/conferences/webauthn-se-debarrasser-des-mots-de-passe-definitivement.md
- src/con/data/2022/conferences/what-s-new-in-caddy-the-webserver-of-api-platform.md
- src/styles/components/home/_cover.scss
- src/styles/settings/_colors.scss
- yarn.lock
It's better to merge https://github.com/api-platform/website/pull/339 before review this PR
> feat: add conference recordings

- src/con/components/2023/home/MissingConferences.tsx
Fixes https://github.com/api-platform/website/issues/366
> replace 2021 confs with 2022 confs

- .github/workflows/cd.yml
- .github/workflows/deploy.yml
- helm/api-platform/templates/pwa-deployment.yaml
- helm/api-platform/templates/secrets.yaml
> Push github key in pwa deployment

- pwa/app/(common)/community/page.tsx
- pwa/app/(common)/events/components/EventsPage.tsx
- pwa/app/(common)/layout.tsx
- pwa/common.tailwind.config.js
- pwa/components/layout/Layout.tsx
- pwa/components/layout/Nav.tsx
- pwa/data/events/api-platform-meetup-at-montpellier.mdx
- pwa/data/events/api-platform-meetup-at-nantes-2019-06.mdx
- pwa/data/events/api-platform-meetup-live-2020-04-24.mdx
- pwa/data/events/api-platform-meetup-live-2020-04-30.mdx
- pwa/data/events/workshop-domain-driven-design-with-API-Platform-3.mdx
- pwa/next.config.mjs
- pwa/package.json
- pwa/pnpm-lock.yaml
- pwa/styles/common.css
- add docsearch component and styles
- fix events warnings
- update canary version
> feat: add docsearch

- .github/workflows/cd.yml
- .github/workflows/cleanup.yml
- .github/workflows/deploy.yml
- helm/api-platform/templates/configmap.yaml
- helm/api-platform/templates/deployment.yaml
- helm/api-platform/values.yaml
> Implement PR deployment and prod / preprod enviroment

- .github/workflows/cd.yml
- .github/workflows/cleanup.yml
- .github/workflows/deploy.yml
- helm/api-platform/templates/configmap.yaml
- helm/api-platform/templates/deployment.yaml
- helm/api-platform/values.yaml
* Implement PR deployment and prod / preprod enviroment
* Restore gcr subdirectory name
* Add tag remover job
* test syntax
* Use GITHUB_ENV
* Use github env in helm
* Enable Build
* Fix syntax
* Try fix on helm release
* Fix release name
* debug cors
* Edit cleanup job
* Fix cors
* Enable build
* Change staging branch name
* Remove bucket
* Change preprod URLs
* edit cors in helm upgrade
* Add prod branch name temp
> Implement PR deployment and prod / preprod enviroment (#402)

- pwa/api/doc/index.ts
- pwa/app/(common)/components/Admin.tsx
- pwa/app/(common)/components/Cover.tsx
- pwa/app/(common)/components/Features.tsx
- pwa/app/(common)/components/Timeline.tsx
- pwa/app/(common)/docs/[...slug]/page.tsx
- pwa/app/(common)/docs/page.tsx
- pwa/app/(common)/resources/colouring-webby/components/Cover.tsx
- pwa/components/common/Link.tsx
- pwa/components/docs/DocMenu.tsx
- pwa/components/layout/Footer.tsx
- pwa/components/layout/Nav.tsx
- pwa/data/footer.ts
- pwa/middleware.tsx
- fix @CecileAmrl last of the last review
- fix doc nav active link
- fix images links
> Fix: various issues

- .github/workflows/deploy.yml
- helm/api-platform/templates/pwa-deployment.yaml
- helm/api-platform/values.yaml
> Add replica count on pwa

- .github/workflows/deploy.yml
| Tickets       | Closes #..., closes #... 
> Add mem request limit on nonprod only

- pwa/app/(common)/docs/[...slug]/page.tsx
- pwa/app/(common)/docs/guide/[slug]/GuidePage.tsx
- pwa/app/(common)/docs/guide/[slug]/page.tsx
Added a link at the end of all pages to allow any user to contribute directly on GitHub
> feat(docs): adding edit link to all pages

- .github/workflows/deploy.yml
Add Lychee to check dead links after each deploy
> ci: add a check for dead links

- helm/api-platform/templates/deployment.yaml
> fix: increase too agressives probes intervals

- .github/workflows/deploy.yml
| Tickets       | 
| Doc PR        | 
Fix bad resources in helm deployment
> ci: fix bad resources

- .github/workflows/deploy.yml
Fix links check by defining env before execute lychee
> ci: define release name before link check

- pwa/data/events/conference-api-platform-au-quotidien-dans-une-entreprise-ecommerce-et-logistique.mdx
- pwa/data/events/conference-dilemmas-and-decisions-what-we-ve-learned-designing-the-new-sylius-api.mdx
- pwa/data/events/conference-keynote-a-deeper-look-into-api-platform-3.mdx
- pwa/data/events/conference-mon-combat-contre-arachnophobie.mdx
- pwa/data/events/conference-pourquoi-je-n-utilise-pas-api-platform.mdx
- pwa/data/events/conference-rex-france-televisions-quand-api-platform-tombe-a-PIC.mdx
Fix event website link on event page when link is local
> fix(events): wrong link format in files data for apip con

- api/Dockerfile
- docker-compose.override.yml
- docker-compose.prod.yml
- docker-compose.yml
Update the Docker config (fix caddy error in CI), the PWA error should be fixed by #464
> feat: update docker config

- pwa/api/doc/guides.ts
- pwa/api/doc/references.ts
- pwa/app/(common)/docs/[version]/guide/[slug]/GuidePage.tsx
- pwa/app/(common)/docs/[version]/guide/[slug]/page.tsx
- pwa/app/(common)/docs/[version]/layout.tsx
- pwa/app/(common)/docs/[version]/reference/[...slug]/page.tsx
- pwa/app/(common)/docs/[version]/references/page.tsx
- pwa/consts.ts
- pwa/get-core-docs.sh
> feat: versioning of guides and references

- pwa/.gitignore
- pwa/api/doc/changelog.tsx
- pwa/app/(common)/docs/[version]/changelog/ChangelogPage.tsx
- pwa/app/(common)/docs/[version]/changelog/page.tsx
- pwa/prebuild.ts
- pwa/tools/get-core-docs.sh
Adding a changelog page for every version
TODO:
> feat: adding changelog

- pwa/api/doc/guides.ts
- pwa/app/(common)/docs/[version]/guides/GuideFilterDropdown.tsx
- pwa/app/(common)/docs/[version]/guides/GuideSummaryPage.tsx
- pwa/app/(common)/docs/[version]/guides/GuideSummaryPart.tsx
- pwa/app/(common)/docs/[version]/guides/page.tsx
- pwa/app/(common)/docs/[version]/layout.tsx
- pwa/app/(common)/docs/components/DocLayout.tsx
- pwa/components/common/inputs/Dropdown.tsx
- pwa/types/index.tsx
Add index of guides page with filter on type and search
> feat: index of guides

- pwa/app/(con)/[locale]/con/2023/review/components/Review/fr.tsx
- pwa/i18n/dictionaries/fr.json
| Tickets       | Closes #..., closes #... 
> fix: review typos

- helm/api-platform/templates/deployment.yaml
- helm/api-platform/values.yaml
add resources requests to php and caddy containers
> add resources to php and caddy containers

- .github/workflows/cd.yml
- .github/workflows/storage.yml
- pwa/api/contributorsRank.ts
- pwa/app/(common)/community/contributors/[slug]/page.tsx
- pwa/contributors.ts
- pwa/package.json
> feat: externalize script to fetch contributors

- pwa/app/(common)/community/page.tsx
| Tickets       | Closes #..., closes #... 
| Doc PR        | api-platform/docs#... 
Fix for the "go to" link on the community cards here https://api-platform.com/community/
Let me know if i need to point this to another branch, the pull request template states "the stable/latest 3.x for bug fixes" but it is a bit unclear which branch this actually is 🙂
> fix: Use the correct go to links on the community cards

- helm/api-platform/templates/pwa-deployment.yaml
- helm/api-platform/values.yaml
Add OpenTelemetry annotation on PWA Pod to auto-inject instrumentation
> add pwa opentelemetry annotation

- helm/api-platform/templates/hpa.yaml
- helm/api-platform/templates/pwa-hpa.yaml
> fix autoscaler/v2

- LICENSE
| Branch?       | `main`
Update the license file according to https://github.com/api-platform/docs/pull/2049.
See https://github.com/api-platform/docs/pull/2049#pullrequestreview-2398729499 and https://github.com/api-platform/docs/pull/2049#issuecomment-2442058257.
> Update LICENSE file from MIT to CC-BY-4.0 version

- .github/workflows/deploy.yml
- helm/api-platform/values.yaml
Do not set pwa pod resources in github action workflow
> do not set resources in workflow

- pwa/app/(con)/[locale]/con/2025/components/HomePage.tsx
- pwa/app/(con)/[locale]/con/[edition]/speakers/[slug]/SpeakerPage.tsx
- pwa/app/(con)/[locale]/con/[edition]/speakers/[slug]/page.tsx
- pwa/app/(con)/[locale]/con/[edition]/speakers/page.tsx
- pwa/i18n/dictionaries/en.json
- pwa/i18n/dictionaries/fr.json
- add hotel informations on 2025 hp
- add other speakers link on speaker single page
> Feat: add hotel informations
